#title: Tete Jordy Mensah
logo: images/IMG_1735 (1) (2) (1).JPG
description: Data enthusiast whose first love was business, now captivated by how data can profoundly enhance business strategies and decision-making. Committed to exploring and solving complex business challenges through meticulous data analysis and actionable insights.
show_downloads: true
theme: jekyll-theme-minimal
